services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atendimento_saude_api
    restart: unless-stopped
    env_file: .env
    ports:
      - '${PORT:-3000}:3000'
    networks:
      - atendimento_saude_net

networks:
  atendimento_saude_net:
    driver: bridge
